### ISSUE TITLE
Compile issue on Windows 

### ISSUE THREAD

**Issue by Niproblema** [steffengy/schannel-rs#110]
```
  Compiling schannel v0.1.25
error[E0432]: unresolved import `windows_sys::Win32::System::SystemInformation`
   --> C:\Users\Jan\.cargo\registry\src\index.crates.io-6f17d22bba15001f\schannel-0.1.25\src\schannel_cred.rs:181:37
    |
181 |     use windows_sys::Win32::System::SystemInformation::OSVERSIONINFOW;
    |                                     ^^^^^^^^^^^^^^^^^ could not find `SystemInformation` in `System`
    |
```

**Comment by steffengy** [comment]
Thanks - 0.1.25 yanked and should work with 0.1.26.

**Comment by Niproblema** [comment]
Thanks 👍
